version: '3.7'

services:
  gym:
    container_name: gym-festo
    build: gym/
    networks:
      - gymnet
  s7client:
    container_name: s7client
    build: s7_client/
    networks:
      - s7clientnet
networks:
  gymnet:
    name: pdmsim_simnet
  s7clientnet:
    name: pdmsim_simnet